_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/tood_r50_fpn.yml',
  '_base_/optimizer.yml',
  '_base_/tood_reader.yml',
]

weights: output/tood_r50_fpn_1x_coco/model_final
log_iter: 100
