_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/optimizer.yml',
  './_base_/yolox_cspdarknet.yml',
  './_base_/yolox_reader.yml'
]
depth_mult: 0.33
width_mult: 0.50

log_iter: 100
weights: output/yolox_s_300e_coco/model_final
